### PR TITLE
Metrics: fail gracefully

### LINKED ISSUE #196: Fail gracefully when retrieving metrics
To avoid [intermittent errors like](https://cirrus-ci.com/task/5628947292487680):

>Exception on the agent! Failed to retrieve resource utilization metrics: failed to query CPU usage: open /sys/fs/cgroup/cpu,cpuacct/system.slice/google-startup-scripts.service/cpuacct.usage: no such file or directory

This file indeed wasn't there for a short period of time, but for the rest of the execution everything was OK.

### PR DESCRIPTION
**Pull request by edigaryev**
~~As for the `-1.0`, we can convert these values to `null` right in the web UI and get something like this:~~

Screen Shot 2021-12-21 at 01 37 54

~~Since we are removing the agent warning generation for metrics, such graph at least gives a glimpse that something is wrong and a "Debugging" modal window can be further investigated for the agent logs.~~

Resolves #196.

### CODE REVIEW

File: internal/executor/metrics/metrics_unsupported.go [hunk 1]
```diff
@@ -8,11 +9,15 @@ import (
 	"github.com/sirupsen/logrus"
 )
 
-func Run(ctx context.Context, logger logrus.FieldLogger) (chan *api.ResourceUtilization, chan error) {
-	resultChan := make(chan *api.ResourceUtilization, 1)
-	errChan := make(chan error, 1)
+type Result struct {
+	Errors              []error
```
Comment (fkorotkov) [inline internal/executor/metrics/metrics_unsupported.go:13]: I wonder if it make sense to deduplicate the errors before sending them. There might be dozens of identical errors. @edigaryev what do you think?

Comment (edigaryev) [reply internal/executor/metrics/metrics_unsupported.go:13]: Good idea, added error deduplication in https://github.com/cirruslabs/cirrus-ci-agent/pull/200/commits/48d8698d6da55828aa565cfa77a97ac2e83529fd.

**Review by fkorotkov — APPROVED** [review]
